### ISSUE TITLE
Resize images breaks LaTeX

### ISSUE THREAD

**Issue by bjonnh** [eschulte/epresent#6] opened 2014-06-17 04:15 UTC
I'm trying to resize the image (in present.org) by using
#+ATTR_HTML: width="100px"
or
#+ATTR_HTML: :width 100px

but when I do that, the image doesn't appear, and I can't see the LaTeX formula anymore.
moreover, the picture doesn't appear neither.

The worse being that sometimes the formula continues to work and sometimes not (but never does the picture appear except when I do org-display-inline-images) and I can't find a way to reproduce that each time.

**Comment by tmalsburg** [comment] 2015-02-26 22:51
@bjonnh see also #17.  It appears that LaTeX formulae work reliably when you place the cursor at the beginning of the document before starting the presentation.  The image-related part of the issue is fixed by 222fdc4665525126ab3f17f1f9fc75580a9186c4.  (Scaling using the HTML attribute doesn't work but isn't really expexted to.)

**Comment by madhavan020985** [comment] 2015-03-03 16:37
I too, am facing problem with #+ATTR_HTML
````lisp
* Picture
#+ATTR_HTML: style="position:absolute;top:50%;left:50%;"
[[file:Pictures/image1.jpg]photo]]
````
I thought, the jpg image will be rendered in page center but it was in its original place, on the left top. In summary, the above css params have no effect in epresent-mode

**Comment by tmalsburg** [comment] 2015-03-03 18:23
I think there is a misunderstanding about the meaning of `ATTR_HTML` and about what epresent does.  The HTML attributes are used when you export an org document to HTML for viewing in a web browser (see http://orgmode.org/worg/org-tutorials/images-and-xhtml-export.html)  When you export to other formats such as LaTeX, they are ignored.  Also, epresent doesn't export the document to another format.  What epresent does is mainly to change how your org document is displayed.  Some parts of the document such as TODO tags and property drawers ar hidden, bigger fonts are used, and only one slide at a time is displayed.  That's about it.  Not very powerful from a design perspective but nevertheless surprisingly useful.  The reason why it's useful is that you can embed code blocks in the document and edit and execute them live during your presentation.  That is not possible when you export the presentation to HTML or LaTeX.

**Closed** 2015-03-09 00:35 UTC
